# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'evento_iOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for evento_iOSApp
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'Charts'

  target 'evento_iOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'evento_iOSAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
